### ISSUE TITLE
64 bit build error lagarith

### ISSUE THREAD

**Issue by Anymix** [XhmikosR/lagarith#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command "yasm -X vc -f x64    -o "D:\lagarith-1.3.27-rel1\src\VS2015\Release\x64\obj\convert.obj" "D:\lagarith-1.3.27-rel1\src\convert.asm"" exited with code 1.	lagarith	D:\lagarith-1.3.27-rel1\src\YASM.targets	45	

pls salve this
im using VS2015

**Comment by XhmikosR** [comment]
You probably don't have yasm in path.

**Comment by Anymix** [comment]
but 32bit is building ok pls help me, thank you

**Comment by Anymix** [comment]
when i building each file in separate, it convert.asm not building, else every file building in 64bit either convert.asm.

**Comment by XhmikosR** [comment]
Works fine for me, sorry.
